version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - RAILS_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
